apiVersion: batch/v1
kind: Job
metadata:
  name: fineract-db-charset-fix
  namespace: fineract
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      serviceAccountName: fineractserver-sa
      restartPolicy: OnFailure
      containers:
      - name: mariadb-charset-fixer
        image: registry.redhat.io/rhel8/mariadb-103
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: null
        command: ["sh", "-c"]
        args:
          - |
            DB_PASS_PLAIN="fineract";
            DB_HOST="fineract-default";
            DEFAULT_DB_NAME="fineract_default";
            
            echo "Esperando y aplicando corrección de Charset a UTF8MB4..."

            # 1. Bucle de espera y conexión como superusuario
            until mysqladmin ping -h $DB_HOST -u fineract -p$DB_PASS_PLAIN --silent; do
              sleep 2
            done
            
            echo "Conexión OK. Aplicando ALTER DATABASE y tablas..."

            # 2. Comando SQL CRÍTICO: Forzar la base de datos a UTF8MB4
            mysql -h $DB_HOST -u fineract -p$DB_PASS_PLAIN -e "
              ALTER DATABASE $DEFAULT_DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
              
              -- Opcional: Esto altera todas las tablas que no son utf8mb4 (necesario si no se crearon correctamente)
              -- SELECT concat('ALTER TABLE ', table_name, ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;') 
              -- FROM information_schema.tables WHERE table_schema = '$DEFAULT_DB_NAME' AND table_type = 'BASE TABLE'
              -- INTO OUTFILE '/tmp/alter_tables.sql';
              -- SOURCE /tmp/alter_tables.sql; 
            "
            if [ $? -eq 0 ]; then
                echo "Charset de '$DEFAULT_DB_NAME' actualizado a UTF8MB4 exitosamente."
            else
                echo "ERROR CRÍTICO: Falló la actualización de charset."
                exit 1
            fi
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: fineract-default
              key: database-user
        - name: DB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fineract-default
              key: database-root-password
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fineract-default
              key: database-password