# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: fineract
    tier: backend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: fineract-backend
      tier: backend
      instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: fineract-backend
        tier: backend
        instance: {{ .Release.Name }}
      annotations:
        # Force a pod restart if secret values change
        checksum/secrets: {{ include "secrets" . | sha256sum }}
    spec:
      containers:
        - name: fineract-backend
          image: "{{ .Values.fineractServer.image.name }}:{{ .Values.fineractServer.image.tag }}"
          envFrom:
            - secretRef:
                name: {{ .Release.Name | quote }}
          env:
            - name: FINERACT_DEFAULT_TENANTDB_HOSTNAME
              value: {{ include "mysql_host" . }}
            - name: fineract_tenants_url
              value: {{ include "mysql_url" . }}
            - name: fineract_tenants_uid
              value: {{ include "mysql_user" . }}
            - name: FINERACT_DEFAULT_TENANTDB_UID
              value: {{ include "mysql_user" . }}
            {{- if .Values.fineractServer.extraEnv }}
            {{- range $key, $value := .Values.fineractServer.extraEnv }}
            - name: {{ $key | quote}}
              value: |-
                {{- tpl $value $ | nindent 16 }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /fineract-provider/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 90
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /fineract-provider/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            timeoutSeconds: 10
          resources:
            {{- .Values.fineractServer.resources | toYaml | nindent 12 }}
