kind: Secret
apiVersion: v1
metadata:
  name: fineract-tenants
  labels:
    app: fineract-tenants
    app.kubernetes.io/name: fineract-tenants
    app.kubernetes.io/part-of: fineract
data:
  database-name: ZmluZXJhY3RfdGVuYW50cw==
  database-password: ZmluZXJhY3Q=
  database-root-password: ZmluZXJhY3Q=
  database-user: ZmluZXJhY3Q=
  fineract_default: ZmluZXJhY3RfdGVuYW50cw==
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fineract-tenants
  labels:
    app: fineract-tenants
    app.kubernetes.io/component: fineract-tenants
    app.kubernetes.io/instance: fineract-tenants
    app.kubernetes.io/name: fineract-tenants
    app.kubernetes.io/part-of: fineract-tenants
    app.openshift.io/runtime: mariadb
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    matchLabels:
      app: fineract-tenants
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fineract-tenants
        app.openshift.io/runtime: mariadb
        deployment: fineract-tenants
    spec:
      volumes:
        - name: fineract-tenants-data
          persistentVolumeClaim:
            claimName: fineract-tenants-data
      serviceAccountName: fineractserver-sa            
      containers:
        - resources:
            limits:
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - MYSQL_PWD="$MYSQL_PASSWORD" mariadb-admin ping -u $MYSQL_USER
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: fineract-tenants
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - MYSQL_PWD="$MYSQL_PASSWORD" mariadb-admin ping -u $MYSQL_USER
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: fineract-tenants
                  key: database-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fineract-tenants
                  key: database-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fineract-tenants
                  key: database-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: fineract-tenants
                  key: database-name
          ports:
            - containerPort: 3306
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: fineract-tenants-data
              mountPath: /var/lib/mysql/data
          terminationMessagePolicy: File
          image: >-
            mariadb:11.4
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fineract-tenants
    app.kubernetes.io/component: fineract-tenants
    app.kubernetes.io/instance: fineract-tenants
    app.kubernetes.io/name: fineract-tenants
    app.kubernetes.io/part-of: fineract-tenants
  name: fineract-tenants
spec:
  ports:
    - name: 3306-tcp
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: fineract-tenants
    deployment: fineract-tenants
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fineract-tenants-data
  labels:
    app: fineract-tenants
    app.kubernetes.io/instance: fineract-tenants
    app.kubernetes.io/name: fineract-tenants
    app.kubernetes.io/part-of: fineract-tenants
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi